openapi: 3.0.3
info:
  title: 3D File Repository API
  description: REST API for managing 3D files
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:5000/api
paths:
  /files:
    get:
      summary: List all 3D files
      responses:
        "200":
          description: List of 3D files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/3DObject"
    post:
      summary: Upload a 3D file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Create3DObject"

      responses:
        "200":
          description: File uploaded successfully

  /files/{fileId}:
    put:
      summary: Rename file
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RenameRequest"
      responses:
        "200":
          description: File renamed successfully
    delete:
      summary: Delete file
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: File deleted successfully

    get:
      summary: Download Original 3D File (Original or Transformed)
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: string
          description: The ID of the 3D file to download. Please use 'buggy' as the default value.
        - in: query
          name: transform
          required: false
          schema:
            $ref: "#/components/schemas/TransformRequest"
      responses:
        "200":
          description: The original 3D file has been successfully downloaded.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

components:
  schemas:
    TransformRequest:
      type: object
      properties:
        scale:
          type: array
          required: true
          items:
            type: number
          maxItems: 3
          description: Scale vector for transformation.
          example: [2, 2, 2]
        translation:
          type: array
          required: true
          items:
            type: number
          maxItems: 3
          description: Translation vector for transformation.
          example: [10, 0, 0]

    RenameRequest:
      type: object
      properties:
        newName:
          type: string
      required:
        - newName

    3DObjectBase:
      type: object
      properties:
        name:
          type: string
          description: Name of the 3D object.
        format:
          type: string
          description: File format of the 3D object (e.g., OBJ, STL). Only OBJ supported now.
        content:
          type: string
          format: binary
          description: File binary, only required when uploading a file.

    3DObject:
      allOf:
        - $ref: "#/components/schemas/3DObjectBase"
        - type: object
          properties:
            id:
              type: string
              format: uuid
              description: Unique identifier for the 3D object.
          required:
            - id

    Create3DObject:
      allOf:
        - $ref: "#/components/schemas/3DObjectBase"
        - type: object
          # No 'id' property required for creation
          required:
            - name
            - format
